As a result of this program, the system and the kernel will be updated!
Don't forget to make backups of the system and data, close unnecessary
programs, make sure that there is at least 25% free disk space, that
the computer is connected to an uninterruptible power supply and the
network is available.

ATTENTION: this operation is irreversible and cannot be interrupted!

If in doubt, press Ctrl-C and consult with someone. If you
haven't changed your mind, press any other key to continue...