#!/bin/bash
### This file is covered by the GNU General Public License
### version 3 or later.
###
### Copyright (C) 2025, ALT Linux Team

#######################################
### Entry point to the moved daemon ###
#######################################

# shellcheck source=./main.sh
. /usr/local/libexec/os-upgrade/main.sh

